import { Hono } from 'hono';

/**
 * Terms and Privacy, served as plain HTML from the API.
 *
 * These are LOAD-BEARING for shipping, not paperwork: the paywall links to both
 * (`TERMS_URL` / `PRIVACY_URL` in the app's constants.ts), App Store Review 3.1.2
 * requires a working EULA and privacy link on any auto-renewing subscription, and
 * Play requires a privacy policy URL on the listing. Both links 404'd before this
 * file existed, which is a rejection.
 *
 * Served here rather than as a separate static site because `vercel.json` already
 * rewrites every path to this app — so this is two routes and no new
 * infrastructure, no second deploy target, and no third place to keep in sync.
 *
 * ⚠️ DRAFTS, NOT LEGAL ADVICE. The facts below are accurate to what this codebase
 * actually does — read `db/schema.ts` before changing any of them — but the
 * bracketed placeholders must be filled and the whole thing reviewed by someone
 * qualified in your jurisdiction before you take money.
 */
export const legal = new Hono();

/** Bump when the substance changes. Users notice a date that never moves. */
const UPDATED = '5 August 2026';

const CONTACT = 'support@rizzcoach.app';

function page(title: string, body: string): string {
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title} · RizzCoach</title>
<style>
  :root { color-scheme: dark light; }
  body {
    margin: 0 auto; padding: 2.5rem 1.25rem 5rem; max-width: 44rem;
    font: 16px/1.65 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: #0A0A12; color: #E8E8F0;
  }
  h1 { font-size: 1.9rem; letter-spacing: -0.02em; margin: 0 0 .25rem; }
  h2 { font-size: 1.15rem; margin: 2.25rem 0 .6rem; color: #fff; }
  .updated { color: #8A8AA0; font-size: .875rem; margin: 0 0 2rem; }
  a { color: #A78BFA; }
  ul { padding-left: 1.25rem; }
  li { margin: .35rem 0; }
  strong { color: #fff; }
  .note {
    border-left: 3px solid #A78BFA; background: rgba(167,139,250,.08);
    padding: .75rem 1rem; margin: 1.5rem 0; border-radius: 0 6px 6px 0;
  }
  footer { margin-top: 3.5rem; padding-top: 1.5rem; border-top: 1px solid #26263A;
           color: #8A8AA0; font-size: .875rem; }
  @media (prefers-color-scheme: light) {
    body { background: #fff; color: #1A1A24; }
    h2, strong { color: #000; }
    .updated, footer { color: #666; }
    footer { border-top-color: #E5E5EA; }
  }
</style>
</head><body>
<h1>${title}</h1>
<p class="updated">Last updated ${UPDATED}</p>
${body}
<footer>
  RizzCoach · <a href="/terms">Terms</a> · <a href="/privacy">Privacy</a> ·
  <a href="mailto:${CONTACT}">${CONTACT}</a>
</footer>
</body></html>`;
}

// ── /terms ───────────────────────────────────────────────────────────────────

legal.get('/terms', (c) =>
  c.html(
    page(
      'Terms of Service',
      `
<p>These terms are a contract between you and <strong>[LEGAL ENTITY NAME]</strong>
("we", "us"), covering the RizzCoach mobile application. By using RizzCoach you
accept them. If you do not, do not use the app.</p>

<h2>1. Who may use RizzCoach</h2>
<p>You must be at least <strong>18 years old</strong>. RizzCoach is built around
adult dating conversations and is not intended for children. If we learn that an
account belongs to someone under 18, we will close it.</p>

<h2>2. What RizzCoach does</h2>
<p>RizzCoach uses AI to suggest opening lines, rewrite dating bios and give
feedback on dating profiles. Suggestions are generated by a machine and are
<strong>entertainment and assistance, not advice</strong>. We do not promise any
outcome — no matches, no replies, no dates, no relationships.</p>

<h2>3. Free usage and subscriptions</h2>
<p>New accounts get <strong>3 free analyses</strong>. After that, continued use
requires RizzCoach Pro:</p>
<ul>
  <li><strong>Weekly</strong> — US$6.99 per week</li>
  <li><strong>Annual</strong> — US$79.99 per year</li>
</ul>
<p>Prices are charged in your local currency and may differ by region and with
applicable taxes. The price shown at purchase is the price that applies.</p>

<div class="note">
<p><strong>Auto-renewal.</strong> Subscriptions renew automatically at the end of
each period unless cancelled at least <strong>24 hours before</strong> it ends.
Your Apple or Google account is charged for renewal within 24 hours of the period
ending.</p>
<p><strong>Cancelling.</strong> Manage or cancel in your device's store settings —
App Store subscriptions on iOS, Google Play subscriptions on Android. Deleting the
app does <em>not</em> cancel a subscription. We cannot cancel it for you.</p>
</div>

<h2>4. Refunds</h2>
<p>Purchases are processed by Apple and Google, not by us, so refunds are governed
by their policies and requested through them. Where the law of your country gives
you a right to withdraw or a refund, that right applies regardless of anything in
this section.</p>

<h2>5. Acceptable use</h2>
<p>Do not use RizzCoach to:</p>
<ul>
  <li>harass, threaten, deceive, impersonate or stalk anyone;</li>
  <li>analyse a person's profile or messages for any purpose other than your own
      conversation with them;</li>
  <li>generate content that is sexual involving minors, hateful, or unlawful;</li>
  <li>break the terms of Tinder, Hinge, Bumble, Instagram, WhatsApp, Snapchat,
      Telegram or any other service you use RizzCoach alongside;</li>
  <li>automate, scrape, resell or reverse-engineer the app or our API.</li>
</ul>
<p>We may suspend or close an account that does any of this, without refund.</p>

<h2>6. Your account</h2>
<p>You are responsible for your password and for what happens under your account.
<strong>There is currently no password reset</strong> — if you lose your password
you lose access to that account and any credits on it. Keep it somewhere safe.</p>
<p>To delete your account and its data, contact
<a href="mailto:${CONTACT}">${CONTACT}</a> from your registered email address.
Deletion is permanent and does not cancel a store subscription — cancel that
separately.</p>

<h2>7. AI content</h2>
<p>Suggestions are produced by a third-party AI model and may be wrong,
inappropriate or generic. <strong>You are responsible for anything you choose to
send.</strong> Read it before you use it. We do not guarantee any suggestion is
accurate, original or suitable.</p>

<h2>8. Availability</h2>
<p>We may change, suspend or discontinue any feature at any time. The AI depends
on services we do not control and may be unavailable. We do not guarantee
uninterrupted service.</p>

<h2>9. Liability</h2>
<p>To the fullest extent the law allows, RizzCoach is provided <strong>"as
is"</strong> and our total liability to you is limited to the amount you paid us
in the <strong>12 months</strong> before the claim. Nothing here excludes
liability that cannot lawfully be excluded.</p>

<h2>10. Changes</h2>
<p>We may update these terms. Continued use after an update means you accept it.
Material changes will be notified in the app.</p>

<h2>11. Governing law</h2>
<p>These terms are governed by the laws of <strong>[JURISDICTION]</strong>, and
disputes will be heard in the courts of <strong>[CITY, COUNTRY]</strong> — without
affecting consumer-protection rights you have where you live.</p>

<h2>12. Contact</h2>
<p><a href="mailto:${CONTACT}">${CONTACT}</a></p>
`,
    ),
  ),
);

// ── /privacy ─────────────────────────────────────────────────────────────────

legal.get('/privacy', (c) =>
  c.html(
    page(
      'Privacy Policy',
      `
<p>This explains what RizzCoach collects, why, and what we do not collect. The
short version: <strong>we do not store your screenshots, your conversations, or
the suggestions we generate.</strong></p>

<h2>1. What we store</h2>
<p>One database row per account, containing:</p>
<ul>
  <li><strong>Email and username</strong> — only if you create an account;</li>
  <li><strong>A password hash</strong> — scrypt, never the password itself;</li>
  <li><strong>An install identifier</strong> and your platform (iOS/Android) and
      app version;</li>
  <li><strong>Usage counters</strong> — how many analyses you have run, to enforce
      the free limit;</li>
  <li><strong>Subscription status</strong> and its expiry, plus an identifier from
      our payment provider.</li>
</ul>

<h2>2. What we do NOT store</h2>
<div class="note">
<p>We do not keep <strong>screenshots, images, message text, bios, profile
details, generated openers, or any analysis result</strong>. There is nowhere in
our database for them to go. Content is sent to the AI, the answer comes back to
your phone, and nothing about it is written down on our side.</p>
</div>
<p>We do not collect your contacts, your location, your photo library, your
microphone, or your dating-app credentials.</p>

<h2>3. The AI</h2>
<p>To generate a suggestion, we send the content you provide — a screenshot, a
bio, a profile description — to <strong>Google's Gemini API</strong>. Google
processes it to produce the response and handles it under its own terms. We send
no account identifier with it, so the content is not linked to you at Google.</p>
<p>See <a href="https://ai.google.dev/gemini-api/terms" rel="noopener">Google's
Gemini API terms</a>.</p>

<h2>4. The Android screen-reading feature</h2>
<p>On Android, RizzCoach offers an optional assistant that reads the conversation
on screen so it can suggest a reply in place. It uses Android's
<strong>Accessibility Service</strong>, and it is <strong>off until you turn it on
by hand</strong> in your phone's settings.</p>
<ul>
  <li>It activates only in supported messaging and dating apps.</li>
  <li>Screen content is used to generate that one suggestion and is
      <strong>not stored and not sent anywhere except the AI</strong>.</li>
  <li>It is never used for advertising, profiling or analytics.</li>
  <li>Turn it off any time in Android Settings → Accessibility.</li>
</ul>

<h2>5. Others who process data for us</h2>
<ul>
  <li><strong>Google (Gemini)</strong> — generates suggestions.</li>
  <li><strong>RevenueCat</strong> — manages subscriptions. Receives an
      account identifier and your purchase state, never your email or password.</li>
  <li><strong>Apple / Google Play</strong> — take the payment. We never see your
      card details.</li>
  <li><strong>Firebase Analytics and Crashlytics</strong> — which screens are used
      and which crashes happen. Events carry no message text, no bios, no names
      and no generated content.</li>
  <li><strong>Vercel and Railway</strong> — host the service and the database.</li>
</ul>
<p>We do not sell your data, and we do not share it for advertising.</p>

<h2>6. How long we keep it</h2>
<p>Your account row exists until you delete the account. Server logs are kept
briefly for debugging and contain no message content, no email addresses and no
usernames.</p>

<h2>7. Your rights</h2>
<p>You can ask us to access, correct, export or delete your data by writing to
<a href="mailto:${CONTACT}">${CONTACT}</a> from your registered email address.
Deleting your account erases the row described in section 1 permanently.</p>
<p>Depending on where you live you may also have rights under the GDPR, the CCPA
or India's DPDP Act, including objecting to processing and complaining to a
regulator.</p>

<h2>8. Children</h2>
<p>RizzCoach is for adults 18 and over. We do not knowingly collect data from
children. If you believe a child has created an account, write to us and we will
delete it.</p>

<h2>9. Security</h2>
<p>Traffic is encrypted in transit, the database connection uses verified TLS, and
passwords are stored as salted scrypt hashes. No system is perfectly secure, but
the most sensitive thing you could lose here — your conversations — is not
something we hold.</p>

<h2>10. Changes</h2>
<p>We will update this page and the date above when practices change, and notify
you in the app if the change is material.</p>

<h2>11. Contact</h2>
<p><strong>[LEGAL ENTITY NAME]</strong>, <strong>[REGISTERED ADDRESS]</strong><br>
<a href="mailto:${CONTACT}">${CONTACT}</a></p>
`,
    ),
  ),
);
